# Aljabar Matrik
Matriks adalah sekumpulan bilangan yang disusun berdasarkan baris dan kolom, serta ditempatkan di dalam tanda kurung. Bisa berupa kurung biasa “( )” atau kurung siku “[ ]”. Suatu matriks diberi nama dengan huruf kapital, seperti A, B, C, dan seterusnya. Komputasi matriks menggunakan numpy, dengan menggunakan array.

$A =$
$
 \begin{bmatrix}
  1 & 3\\
  2 & 1
 \end{bmatrix}
$

$  B =$
$
 \begin{bmatrix}
  3 & 0 & 4\\
  -1 & -2 & 1
 \end{bmatrix}
$

$  C =$
$
 \begin{bmatrix}
  -2 & 1
 \end{bmatrix}
$

$  D =$
$
 \begin{bmatrix}
  2 \\
  6 
 \end{bmatrix}
$

Ukuran matriks disebut ordo. Ordo matriks ini berdasarkan dari banyaknya baris dikali banyaknya kolom pada matriks. Jadi, jika jumlah baris matriks A adalam m dan kolomnya adalah n, maka penulisannya adalah $A_{m x n}$. Masing-masing bilangan yang terdapat di dalam matriks disebut elemen matriks. Elemen-elemen tersebut dinotasikan dengan huruf kecil dan diberi indeks yang menyatakan letak baris dan kolomnya. Sehingga jika ada elemen matriks A pada baris ke-i dan kolom ke-j, maka penulisannya adalah $a_{ij}$.

*Catatan :* Matriks yang hanya memiliki 1 kolom seperti pada matriks D biasa disebut **vektor**.

## Implementasi dengan numpy

In [13]:
import numpy as np
A = np.array([[1,3,-2],[2,4,-1],[3,-6,8]])
B = np.array([[2,-3,4],[-1,-2,1],[4,-5,7]])
C = np.array([[-2,1,-6],[4,-3,9]])
D = np.array([[2,8,2],[-4,5,6],[7,-3,1]])
print(B)
print(C)

[[ 2 -3  4]
 [-1 -2  1]
 [ 4 -5  7]]
[[-2  1 -6]
 [ 4 -3  9]]


In [3]:
# Cara buat matrix dengan cepat menggunakan bilangan yang random

AAA = np.random.randint(10,size=(3,3))
print(AAA)

[[9 5 7]
 [8 8 7]
 [7 3 9]]


In [4]:
#Cara menentukan ukuran matriks:
#  namamatriks.shape
print(C.shape)

#Cara menentukan jumlah baris:
#  namamatriks.shape[0]
print(C.shape[0])

#Cara menentukan jumlah kolom:
#  namamatriks.shape[1]
print(C.shape[1])

(2, 3)
2
3


## Implementasi dengan sympy

In [5]:
import sympy as sy
a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z =\
sy.symbols('a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z', real = True)
A = sy.Matrix([[a, b, c], [d, e, f]])
A + A

Matrix([
[2*a, 2*b, 2*c],
[2*d, 2*e, 2*f]])

## Operasi-operasi Matrik
Untuk definisi, dimisalkan A dan C adalah matriks $m x n$, B adalah matriks $n x k$, dan c adalah suatu bilangan/skalar.
1. Operasi Penjumlahan dan pengurangan. Operasi ini hanya akan dieksekusi jika ukuran kedua matriks sama.
- $A+B=B+A$
- $A+(B+C)=(A+B)+C$
- $A+C=C+A$
- $A+(−A)=A-A=0$
- $(A + B)_{ij} = a_{ij} + b_{ij}$
- $A + O = A$, dimana O adalah matriks nol

In [7]:
K = B + D
print('K =', K)

K = [[ 4  5  6]
 [-5  3  7]
 [11 -8  8]]


In [14]:
c = 2
d = 4
e = c + d
G = (c+d)*A
H = (c*A) + (d*A)
print('e =', e)
print('G =', G)
print('H =', H)
i = c - d
j = (c-d)*A
k = (c*A)-(d*A)
print('i =', i)
print('j =', j)
print('k =', k)

e = 6
G = [[  6  18 -12]
 [ 12  24  -6]
 [ 18 -36  48]]
H = [[  6  18 -12]
 [ 12  24  -6]
 [ 18 -36  48]]
i = -2
j = [[ -2  -6   4]
 [ -4  -8   2]
 [ -6  12 -16]]
k = [[ -2  -6   4]
 [ -4  -8   2]
 [ -6  12 -16]]


2. Operasi Perkalian.
- Perkalian dengan skalar $c$ dan $d$.
    - $(c + d)A = cA + dA$
    - $c(dA) = (cd)A$
    - $c(A + B) = cA + cB$
    - $c(AB) = (cA)B = A(cB)$
- Perkalian dua matriks. Hanya bisa dieksekusi jika jumlah kolom matriks A dan jumlah baris matriks B sama.
    - $A \cdot B\neq B \cdot A$
    - $A(B \cdot C) = (A \cdot B)C$
    - $A_{ij} \cdot B_{jk} = E_{il}$

In [15]:
print(A)
print("c x A =", c*A)

[[ 1  3 -2]
 [ 2  4 -1]
 [ 3 -6  8]]
c x A = [[  2   6  -4]
 [  4   8  -2]
 [  6 -12  16]]


In [8]:
print("A x B =",B*D)

A x B = [[  4 -24   8]
 [  4 -10   6]
 [ 28  15   7]]


In [9]:
print("A x B =", B@D)

A x B = [[ 44 -11 -10]
 [ 13 -21 -13]
 [ 77 -14 -15]]


In [10]:
print("A x C", B@C)
# Tidak bisa dioperasikan karena jumlah kolom A tidak sama dengan jumlah baris C. Sehingga terjadi error

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

3. Operasi Campuran. Ini menerapkan beberapa operasi di atas. Misalkan terdapat matriks $𝐴$, $B$, $C$ dan $d,e$ sembarang skalar yang sedemikian rupa sehingga berlaku :
- $A(B+C)=A \cdot B + A \cdot C$
- $(B+C)A=B \cdot A + C \cdot A$
- $d(A+B)=dA+dB$
- $(d+e)A=dA+eA$
- $(d \cdot e)A=d(eA)$
- $d(B \cdot C)=(dB)C=B(dC)$

In [17]:
print(A@(B+D))
print(A@B+A@D)

[[-33  30  11]
 [-23  30  32]
 [130 -67  40]]
[[-33  30  11]
 [-23  30  32]
 [130 -67  40]]


In [19]:
print((c+d)*A)
print(c*A+d*A)

[[  6  18 -12]
 [ 12  24  -6]
 [ 18 -36  48]]
[[  6  18 -12]
 [ 12  24  -6]
 [ 18 -36  48]]


## *Matriks Transpose*

Transpose adalah operasi yang menukar setiap baris menjadi kolom dan sebaliknya, yang umumnya dilambangkan sebagai $A^T$. Diperkenalkan pada tahun 1958 oleh matematikawan Inggris bernama Arthur Cayley.

Adapun matriks transpose yang dikali dengan matriks awal disebut Matriks Covarian.

**Karakteristik :**

- $(A^T)^T = A$
- $(A+B)^T = A^T + B^T$
- $(cA)^T = cA^T$
- $(AB)^T = B^T A^T$

In [ ]:
# Matriks Awal
print(B)
print(end="\n")

# Matriks Transpose
B_T = B.transpose()
print(B_T)
print(end="\n")

# Matriks Covarian
cov = B * B_T
print(cov)

[[ 2 -3  4]
 [-1 -2  1]
 [ 4 -5  7]]

[[ 2 -1  4]
 [-3 -2 -5]
 [ 4  1  7]]

[[ 4  3 16]
 [ 3  4 -5]
 [16 -5 49]]


In [ ]:
import numpy as np
A = np.array([[1,3,-2],[2,4,-1],[3,-6,8]])
B = np.array([[2,-3,4],[-1,-2,1],[4,-5,7]])
C = np.array([[-2,1,-6],[4,-3,9]])
D = np.array([[2,8,2],[-4,5,6],[7,-3,1]])
t = A*B*D
print(t)
print(" ")
tt = t.transpose()
print(tt)
print(" ")
a = A.transpose()
b = B.transpose()
dd = D.transpose()
print(a*b*dd)
print(" ")
abd = (A+B)*D
ABD = abd.transpose()
print(ABD)
print(" ")

[[  4 -72 -16]
 [  8 -40  -6]
 [ 84 -90  56]]
 
[[  4   8  84]
 [-72 -40 -90]
 [-16  -6  56]]
 
[[  4   8  84]
 [-72 -40 -90]
 [-16  -6  56]]
 
[[ 6 -4 49]
 [ 0 10 33]
 [ 4  0 15]]
 


## *Matriks Elementer*

Matriks elementer adalah matriks identitas yang mengalami suatu operasi baris elementer.

**Operasi Baris Elementer (OBE)**

Setiap baris matriks dilambangkan $R_i$ dengan i sebagai urutan baris. Pada sebuah matriks, kita dapat melakukan operasi-operasi :
- Mengalikan suatu baris dengan bilangan tak nol. Simbolnya $kR_i \rightarrow R_i$ yang artinya baris ke-i berubah setelah dikalikan k.
- Menambahkan kelipatan suatu baris pada baris lain. Simbolnya $R_i + kR_i \rightarrow R_i$ yang artinya baris ke-i berubah setelah dilakukan penjumlahan $R_i + kR_i$.
- Menukarkan posisi dua baris. Simbolnya $R_i \leftrightarrow R_j$.

Contoh :

In [ ]:
Aa = sy.randMatrix(3, percent=80); Aa

Matrix([
[15, 44, 58],
[ 0, 33, 91],
[82,  0, 52]])

In [ ]:
E = sy.Matrix([[0,1,0],[1,0,0],[0,0,1]]);E

Matrix([
[0, 1, 0],
[1, 0, 0],
[0, 0, 1]])

In [ ]:
E*A

Matrix([
[2,  4, -1],
[1,  3, -2],
[3, -6,  8]])

## *Matriks Identitas*
Matriks Identitas adalah matriks bujur sangkar yang mana seluruh nilainya adalah 0 kecuali salah satu diagonalnya yang bernilai 1. Dilambangkan dengan ***I***.

Contoh :

$I_{4x4} =$
$
 \begin{bmatrix}
  1 & 0 & 0 & 0 \\
  0 & 1 & 0 & 0 \\
  0 & 0 & 1 & 0 \\
  0 & 0 & 0 & 1 
 \end{bmatrix}
$

In [ ]:
import numpy as np
I5 = np.eye(5)
print(I5)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


## Perkalian Matriks dengan Perulangan

Pada kode di bawah, terdapat output error karena jumlah kolom matriks A adalah tiga, sedangkan baris dari matriks C hanya 2. Sedangkan jika dibalik, maka outputnya berupa angka yang telah dikalikan sesuai operasi perkalian matriks.

In [ ]:
#Fungsi Python untuk mendisplay matrix
def display_matrix(mat):
  if mat == None:
    print("error matrix")
  else:
    for row in mat:
      for elem in row:
        print(elem, end='   ')
      print(end="\n")

# Fungsi untuk mengalikan matrix
def mul_matrix(a,b):
  if len(a[0]) != len(b):
    print(f"error --- require {len(a[0])} but found {len(b)}")
    return None
  hasil = []
  for x in range(len(a)):
    result1 = []
    for y in range(len(b[0])):
      total = 0
      for z in range(len(a[0])):
        total += a[x][z] * b[z][y]
      result1.append(total)
    hasil.append(result1)
  return hasil

hasil_kali = mul_matrix(A,C)
display_matrix(hasil_kali)
print(end="\n")
hasil_kali2 = mul_matrix(C,A)
display_matrix(hasil_kali2)
print(end="\n")

error --- require 3 but found 2
error matrix

-18   34   -45   
25   -54   67   

