# Determinan
Determinan adalah nilai yang dapat dihitung dari unsur-unsur suatu matrik persegi. Determinan merupakan ukuran skalar dari semua matriks. Berlaku pada matriks bujur sangkar. Contoh : $A_{nxn}$

In [3]:
import numpy as np
A = np.array([[3,4],[1,0]])
print(A)
np.linalg.det(A)

[[3 4]
 [1 0]]


-4.0

In [4]:
B = np.array([[1,2,3],[2,3,4],[3,4,5]])
print(B)
print(np.linalg.det(B))

[[1 2 3]
 [2 3 4]
 [3 4 5]]
0.0


## Sifat-sifat Determinan

### 1. Determinan dari matriks identitas adalah 1. Contoh:

In [5]:
C = np.array([[1,0],[0,1]])
print(C)
np.linalg.det(C)

[[1 0]
 [0 1]]


1.0

In [6]:
D = np.array([[1,0,0],[0,1,0],[0,0,1]])
print(D)
np.linalg.det(D)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


1.0

### 2. Determinan dari matriks AB sama dengan determinan matriks A dikali determinan matriks B.

$det(AB) = det(A).det(B)$

In [7]:
def RowSwap(A,k,l):
# =============================================================================
#     A is a NumPy array.  RowSwap will return duplicate array with rows
#     k and l swapped.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        temp = B[k][j]
        B[k][j] = B[l][j]
        B[l][j] = temp

    return B

def RowScale(A,k,scale):
# =============================================================================
#     A is a NumPy array.  RowScale will return duplicate array with the
#     entries of row k multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[k][j] *= scale

    return B

def RowAdd(A,k,l,scale):
# =============================================================================
#     A is a numpy array.  RowAdd will return duplicate array with row
#     l modifed.  The new values will be the old values of row l added to
#     the values of row k, multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[l][j] += B[k][j]*scale

    return B

In [8]:
E = np.array([[3,5,1],[2,6,2],[1,3,1]])
F = np.array([[1,1,2],[1,1,3],[2,1,2]])
G = E@F
print(E)
e = np.linalg.det(E)
print(e)
print(F)
f = np.linalg.det(F)
print(f)
print("det(E) x det(F) :", e*f)
print(G)
g = np.linalg.det(G)
print(g)

[[3 5 1]
 [2 6 2]
 [1 3 1]]
0.0
[[1 1 2]
 [1 1 3]
 [2 1 2]]
1.0
det(E) x det(F) : 0.0
[[10  9 23]
 [12 10 26]
 [ 6  5 13]]
0.0


### 3. Jika $I=A.A^{-1}$ maka $det(I)=det(A).det(A^{-1})$. Sehingga, $det(A^{-1})=\frac{1}{det(A)}$

In [9]:
print(A)
print(C)

[[3 4]
 [1 0]]
[[1 0]
 [0 1]]


In [10]:
A1 = RowSwap(A,0,1,)
C1 = RowSwap(C,0,1)
print(A1)
print(C1)

[[1. 0.]
 [3. 4.]]
[[0. 1.]
 [1. 0.]]


In [11]:
A2 = RowAdd(A1,0,1,-3)
C2 = RowAdd(C1,0,1,-3)
print(A2)
print(C2)

[[1. 0.]
 [0. 4.]]
[[ 0.  1.]
 [ 1. -3.]]


In [12]:
A3 = RowAdd(A2,1,1,-3/4)
C3 = RowAdd(C2,1,1,-3/4)
print(A3)
print(C3)

[[1. 0.]
 [0. 1.]]
[[ 0.    1.  ]
 [ 0.25 -0.75]]


In [13]:
print(A)
print(C3)
I = A@C3
print(I)

[[3 4]
 [1 0]]
[[ 0.    1.  ]
 [ 0.25 -0.75]]
[[1. 0.]
 [0. 1.]]


Operasi-operasi di atas menunjukkan bahwa perkalian $A$ dengan $A^{-1}$ hasilnya adalah matriks Identitas.

### 4. Penukaran kolom atau baris matriks akan mengubah tanda determinan.

In [14]:
A = np.array([[1,4,2],[1,1,1],[3,2,1]])
print(A)
round(np.linalg.det(A))

[[1 4 2]
 [1 1 1]
 [3 2 1]]


5

In [15]:
# Penukaran baris
A1 = RowSwap(A,0,1)
print(A1)
round(np.linalg.det(A1))

[[1. 1. 1.]
 [1. 4. 2.]
 [3. 2. 1.]]


-5

In [16]:
# Penukaran kolom
A2 = np.array([[1,2,4],[1,1,1],[3,1,2]])
print(A)
round(np.linalg.det(A1))

[[1 4 2]
 [1 1 1]
 [3 2 1]]


-5

### 5. Jika nilai-nilai suatu baris atau kolom pada sebuah matriks merupakan kelipatan dari nilai-nilai baris atau kolom lainnya, maka determinannya adalah 0.

In [17]:
B = np.array([[1,4,2],[2,8,4],[3,2,1]])
print(B)
round(np.linalg.det(B))

[[1 4 2]
 [2 8 4]
 [3 2 1]]


0

In [18]:
B1 = np.array([[1,4,2],[2,8,4],[1,4,1]])
print(B1)
round(np.linalg.det(B1))

[[1 4 2]
 [2 8 4]
 [1 4 1]]


0

### 6. Jika determinan skalar k dan determinan matriks $A_{n x n}$ dikalikan, maka $det(k.A)=k^n.det(A)$.

In [19]:
print(A)
print(round(np.linalg.det(A)))

[[1 4 2]
 [1 1 1]
 [3 2 1]]
5


In [20]:
k = 2
print(k*A)
print(round(np.linalg.det(k*A)))

[[2 8 4]
 [2 2 2]
 [6 4 2]]
40


### 7. Melakukan operasi baris elementer terhadap matriks tidak akan mengubah determinan dan inversnya.

In [21]:
B = np.array([[1,4,2],[0,-3,-1],[3,2,1]])
print(B)
print(round(np.linalg.det(B)))

[[ 1  4  2]
 [ 0 -3 -1]
 [ 3  2  1]]
5


### 8. Determinan Transpose matriks A sama dengan determinan matriks A

In [22]:
A = np.array([[1,1,3],[4,1,2],[2,1,1]])
print(A)
print(round(np.linalg.det(A)))

[[1 1 3]
 [4 1 2]
 [2 1 1]]
5


In [23]:
A1 = np.transpose(A)
print(A1)
print(round(np.linalg.det(A1)))

[[1 4 2]
 [1 1 1]
 [3 2 1]]
5


## Mencari determinan dengan Ekspansi Kofaktor
Terdapat matrix A yang berukuran $nxn$. Minor suatu matriks 𝐴 dilambangkan dengan 𝑀𝑖j adalah determinan matriks bagian dari matriks 𝐴 yang diperoleh dengan cara menghilangkan elemen – elemennya pada baris ke-𝑖 dan elemen elemen pada kolom ke-𝑗. Dengan demikian untuk matriks 1 x 1, kita tidak bisa mendapatkan minornya. Minor kita bisa dapatkan pada matriks persegi 2 x 2, 3 x 3, dan seterusnya.Sedangkan kofaktor adalah hasil perkalian minor dengan suatu angka yang besarnya menuruti suatu aturan yaitu $(-1)^{i+j}$ dimana i adalah baris dan j adalah kolom. Kofaktor suatu elemen baris ke-𝑖 dan kolom ke-𝑗 dari matriks A dilambangkan dengan $C^{ij}$.

$C^{ij} = (-1)^{i+j} M^{ij}$

-> Ekspansi kofaktor baris i

$det(A)=a_{i1}C_{i1}+a_{i2}C_{i2}+ \cdots +a_{in}C_{in}$

-> Ekspansi kofaktor kolom j

$det(A)=a_{1j}C_{1j}+a_{2j}C_{2j}+ \cdots +a_{nj}C_{nj}$

Diberikan Matriks 4x4:

$A =$
$
 \begin{bmatrix}
  -1 & 0 & 0 & -2 \\
  1 & 0 & 5 & -5 \\
  0 & 1 & 4 & 0  \\
  0 & 0 & 5 & 0 
 \end{bmatrix}
$

Determinan: $det(A)=a_{41}C_{41}+a_{42}C_{42}+ a_{43}C_{43} +a_{44}C_{44}$

Jabarkan satu per satu. 
- $a_{41}$

$A =$
$
 \begin{bmatrix}
  \vdots & 0 & 0 & -2 \\
  \vdots & 0 & 5 & -5 \\
  \vdots & 1 & 4 & 0  \\
  \ddots & \cdots & \cdots & \cdots 
 \end{bmatrix}
$

$det(A)=0(-1)^{4+1}$
$
 \begin{vmatrix}
  0 & 0 & -2 \\
  0 & 5 & -5 \\
  1 & 4 & 0
 \end{vmatrix}
$
$+a_{42}C_{42}+ a_{43}C_{43} +a_{44}C_{44}$

- $a_{42}$

$A =$
$
 \begin{bmatrix}
  -1 & \vdots & 0 & -2 \\
  1 & \vdots & 5 & -5 \\
  0 & \vdots & 4 & 0  \\
  \cdots & \ddots & \cdots & \cdots 
 \end{bmatrix}
$

$det(A)=0(-1)^{4+1}$
$
 \begin{vmatrix}
  0 & 0 & -2 \\
  0 & 5 & -5 \\
  1 & 4 & 0
 \end{vmatrix}
$
$+0(-1)^{4+2}$
$
 \begin{vmatrix}
  -1 & 0 & -2 \\
  1 & 5 & -5 \\
  0 & 4 & 0
 \end{vmatrix}
$
$+ a_{43}C_{43} +a_{44}C_{44}$

- $a_{43}$

$A =$
$
 \begin{bmatrix}
  -1 & 0 & \vdots & -2 \\
  1 & 0 & \vdots & -5 \\
  0 & 1 & \vdots & 0  \\
  \cdots & \cdots & \ddots & \cdots 
 \end{bmatrix}
$

$det(A)=0(-1)^{4+1}$
$
 \begin{vmatrix}
  0 & 0 & -2 \\
  0 & 5 & -5 \\
  1 & 4 & 0
 \end{vmatrix}
$
$+0(-1)^{4+2}$
$
 \begin{vmatrix}
  -1 & 0 & -2 \\
  1 & 5 & -5 \\
  0 & 4 & 0
 \end{vmatrix}
$
$+ (-5)(-1)^{4+3}$
$
 \begin{vmatrix}
  -1 & 0 & -2 \\
  1 & 0 & -5 \\
  0 & 1 & 0
 \end{vmatrix}
$
$+a_{44}C_{44}$

- $a_{44}$

$A =$
$
 \begin{bmatrix}
  -1 & 0 & 0 & \vdots \\
  1 & 0 & 5 & \vdots \\
  0 & 1 & 4 & \vdots \\
  \cdots & \cdots & \cdots & \ddots 
 \end{bmatrix}
$

$det(A)=0(-1)^{4+1}$
$
 \begin{vmatrix}
  0 & 0 & -2 \\
  0 & 5 & -5 \\
  1 & 4 & 0
 \end{vmatrix}
$
$+0(-1)^{4+2}$
$
 \begin{vmatrix}
  -1 & 0 & -2 \\
  1 & 5 & -5 \\
  0 & 4 & 0
 \end{vmatrix}
$
$+ (-5)(-1)^{4+3}$
$
 \begin{vmatrix}
  -1 & 0 & -2 \\
  1 & 0 & -5 \\
  0 & 1 & 0
 \end{vmatrix}
$
$+0(-1)^{4+4}$
$
 \begin{vmatrix}
  -1 & 0 & 0 \\
  1 & 0 & 5 \\
  0 & 1 & 4
 \end{vmatrix}
$

Persamaan determinan kemudian dioperasikan.

$det(A)=0(-1)^{4+1}$
$
 \begin{vmatrix}
  0 & 0 & -2 \\
  0 & 5 & -5 \\
  1 & 4 & 0
 \end{vmatrix}
$
$+0(-1)^{4+2}$
$
 \begin{vmatrix}
  -1 & 0 & -2 \\
  1 & 5 & -5 \\
  0 & 4 & 0
 \end{vmatrix}
$
$+ (-5)(-1)^{4+3}$
$
 \begin{vmatrix}
  -1 & 0 & -2 \\
  1 & 0 & -5 \\
  0 & 1 & 0
 \end{vmatrix}
$
$+0(-1)^{4+4}$
$
 \begin{vmatrix}
  -1 & 0 & 0 \\
  1 & 0 & 5 \\
  0 & 1 & 4
 \end{vmatrix}
$

Untuk bagian yang hasilnya tidak nol akan kembali dioperasikan dengan Ekspansi Kofaktor seperti cara sebelumnya.

$det(A)=0+0+$
$+ (-5)(-1)^{4+3}$
$
 \begin{vmatrix}
  -1 & 0 & -2 \\
  1 & 0 & -5 \\
  0 & 1 & 0
 \end{vmatrix}
$
$+0$

$det(A)=5$
$
 \begin{vmatrix}
  -1 & 0 & -2 \\
  1 & 0 & -5 \\
  0 & 1 & 0
 \end{vmatrix}
$
$=5$
$\left( 0(-1)^{3+1}
 \begin{vmatrix}
  0 & -2 \\
  0 & -5
 \end{vmatrix}
+1(-1)^{3+2}
 \begin{vmatrix}
  -1 & -2 \\
  1 & -5
 \end{vmatrix}
+0(-1)^{3+3}
 \begin{vmatrix}
  -1 & 0 \\
  1 & 0
 \end{vmatrix}
\right)$

Matriks yang tadinya berukuran 3x3 berubah menjadi berukuran 2x2. Determinan menjadi lebih mudah untuk ditemukan.

$det(A)=5$
$\left( (-1)
 \begin{vmatrix}
  -1 & -2 \\
  1 & -5
 \end{vmatrix}
\right)$
$=5(-1(5-(-2))) = 5(-1(7)) = 5(-7) = -35$

## Matriks Segitiga Atas

Matriks segitiga atas merupakan bentuk matriks persegi yang elemen di bawah diagonal utamanya bernilai nol, sehingga seolah-olah berbentuk segitiga.

In [ ]:
A = np.array([[2,3,1,2],[0,1,2,1],[0,0,5,2],[0,0,0,3]])
print(A)
print(round(np.linalg.det(A)))

[[2 3 1 2]
 [0 1 2 1]
 [0 0 5 2]
 [0 0 0 3]]
30


In [ ]:
A = np.array([[1,4,2],[0,4,1],[0,0,1]])
print(A)
print(round(np.linalg.det(A)))

[[1 4 2]
 [0 4 1]
 [0 0 1]]
4


In [ ]:
A = np.array([[4,2],[0,1]])
print(A)
print(round(np.linalg.det(A)))

[[4 2]
 [0 1]]
4
