# Matriks Invers
Invers matriks A adalah suatu matriks baru yang berkebalikan dengan matriks A dengan notasi $A^{-1}$. Jika matriks tersebut dikalikan dengan invers matriksnya, maka akan terbentuk matriks identitas.

Sifat-sifatnya :
- $A^{-1}$ dapat diinverskan menjadi $(A^{-1})^{-1} = A$
- $A^k$ dapat diinverskan $(A^k)^{-1} = A^{-1} A^{-1}...A^{-1} = (A^{-1})^k = A^{-k}$
- $cA$ dapat diinverskan menjadi $(cA)^{-1} = 1/c * A^-1, c = 0$
- $A^T$ dapat diinverskan menjadi $(A^T)^{-1} = (A^{-1})^T$

In [2]:
import numpy as np

In [3]:
def RowSwap(A,k,l):
# =============================================================================
#     A is a NumPy array.  RowSwap will return duplicate array with rows
#     k and l swapped.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        temp = B[k][j]
        B[k][j] = B[l][j]
        B[l][j] = temp

    return B

def RowScale(A,k,scale):
# =============================================================================
#     A is a NumPy array.  RowScale will return duplicate array with the
#     entries of row k multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[k][j] *= scale

    return B

def RowAdd(A,k,l,scale):
# =============================================================================
#     A is a numpy array.  RowAdd will return duplicate array with row
#     l modifed.  The new values will be the old values of row l added to
#     the values of row k, multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[l][j] += B[k][j]*scale

    return B

## Mencari Invers Matriks dengan Metode Eliminasi Gauss-Jordan

Eliminasi Gauss-Jordan adalah prosedur pemecahan sistem persamaan linear dengan mengubahnya menjadi bentuk matriks eselon baris tereduksi dengan Operasi Baris Elementer. Matriks Eselon Baris Tereduksi adalah sebuah bentuk matriks eselon baris yang lebih disederhanakan yang bertujuan agar lebih mudah dalam pencarian pemecahan (solusi) dari suatu sistem persamaan. Agar mencapai bentuk eselon baris tereduksi diperlukan 4 sifat, yaitu :
- Jika suatu baris yang semua elemennya tidak nol semua, maka bilangan tidak nol pertama dalam baris tersebut adalah 1. Bisa kita sebut dengan 1 utama/pertama.
- Jika terdapat baris yang semuanya elemennya bernilai nol, maka semua baris yang seperti itu harus dikelompokkan dan diletakkan  di bawah matriks.
- Setiap dua baris yang berurutan yang memenuhi sifat ke-1, maka 1 utama dalam baris yang lebih rendah letaknya harus lebih kekanan dari 1 utama dalam baris yang lebih tinggi.
- Sifat ke-4 ini merupakan sifat khusus yaitu setiap kolom yang mengandung 1 utama maka elemen-elemen lain selain 1 utama bernilai nol.

Setelah memahami bentuk eselon baris tereduksi selanjutnya kita akan mencoba memecahkan sistem persamaan linear dengan eliminasi gauss-jordan yakni dengan cara merepresentasikan kedalam  matriks kemudian mengubahnya kebentuk eselon baris tereduksi.

Persamaan :

$x_1 + x_2 + \frac{1}{2}x_3 + \frac{1}{2}x_4 = 9$

$x_2 - \frac{1}{2}x_4 + x_4 - \frac{1}{2}x_5 = 17$

$x_3 + 5x_4 - 2x_5 - 2x_6 = 5$

Berikut langkah-langkahnya :

In [4]:
a = np.array([[1,1,0.5,0.5,0,0],[0,1,-0.5,1,-0.5,0],[0,0,1,5,-2,-2]])
print(a)

[[ 1.   1.   0.5  0.5  0.   0. ]
 [ 0.   1.  -0.5  1.  -0.5  0. ]
 [ 0.   0.   1.   5.  -2.  -2. ]]


In [10]:
# Kalikan baris indeks ke-2 dengan 1/2
b = RowScale(a,2,1/2)
print(b)

[[ 1.   1.   0.5  0.5  0.   0. ]
 [ 0.   1.  -0.5  1.  -0.5  0. ]
 [ 0.   0.   0.5  2.5 -1.  -1. ]]


In [11]:
# Tambahkan baris indeks ke-2 yang sudah dikalikan 1 ke baris indeks ke-1
c = RowAdd(b,2,1,1)
print(c)

[[ 1.   1.   0.5  0.5  0.   0. ]
 [ 0.   1.   0.   3.5 -1.5 -1. ]
 [ 0.   0.   0.5  2.5 -1.  -1. ]]


In [12]:
# Tambahkan baris indeks ke-2 yang sudah dikalikan -1 ke baris indeks ke-0
d = RowAdd(c,2,0,-1)
print(d)

[[ 1.   1.   0.  -2.   1.   1. ]
 [ 0.   1.   0.   3.5 -1.5 -1. ]
 [ 0.   0.   0.5  2.5 -1.  -1. ]]


In [13]:
# Kalikan baris indeks ke-2 dengan 2
e = RowScale(d,2,2)
print(e)

[[ 1.   1.   0.  -2.   1.   1. ]
 [ 0.   1.   0.   3.5 -1.5 -1. ]
 [ 0.   0.   1.   5.  -2.  -2. ]]


In [14]:
# Tambahkan baris indeks ke-1 yang sudah dikalikan -1 ke baris indeks ke-0
f = RowAdd(e,1,0,-1)
print(f)

# Matriks sudah berubah menjadi matriks invers.

[[ 1.   0.   0.  -5.5  2.5  2. ]
 [ 0.   1.   0.   3.5 -1.5 -1. ]
 [ 0.   0.   1.   5.  -2.  -2. ]]


In [15]:
# Dikalikan untuk menyelesaikan persamaan

b = np.array([[9],[17],[5]])

c = np.array([[-5.5,2.5,2],[3.5,-1.5,-1],[5,-2,-2]])

print(c@b)

[[3.]
 [1.]
 [1.]]


## Menyelesaikan Sistem Persamaan Linear 4 Variabel Menggunakan Matrix Invers dengan Metode Eliminasi Gauss-Jordan

Penyelesaian :

$AX = B \\
X = A^{-1} B$

Persamaan :
- $2x_1 - 3x_4 = 3$
- $2x_2 + 2x_3 - 4x_4 = 4$
- $3x_1 + 3x_3 = 6$
- $-2x_2 - 2x_3 + 5x_4 = -3$

Berikut langkah-langkahnya :

In [46]:
C = np.array([[2,0,0,-3],[0,2,2,-4],[3,0,3,0],[0,-2,-2,5]])
I = np.array([[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]])
X = np.array([[3],[4],[6],[-3]])
print(C)
print(I)
print(end="\n")
print(X)

[[ 2  0  0 -3]
 [ 0  2  2 -4]
 [ 3  0  3  0]
 [ 0 -2 -2  5]]
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]

[[ 3]
 [ 4]
 [ 6]
 [-3]]


In [13]:
# Tambahkan baris indeks ke-0 yang sudah dikalikan -3/2 ke baris indeks ke-2
C1 = RowAdd(C,0,2,-3/2)
print(C1)
I1 = RowAdd(I,0,2,-3/2)
print(I1)

[[ 2.   0.   0.  -3. ]
 [ 0.   2.   2.  -4. ]
 [ 0.   0.   3.   4.5]
 [ 0.  -2.  -2.   5. ]]
[[ 1.   0.   0.   0. ]
 [ 0.   1.   0.   0. ]
 [-1.5  0.   1.   0. ]
 [ 0.   0.   0.   1. ]]


In [14]:
# Tambahkan baris indeks ke-1 yang sudah dikalikan 1 ke baris indeks ke-3
C2 = RowAdd(C1,1,3,1)
print(C2)
I2 = RowAdd(I1,1,3,1)
print(I2)

[[ 2.   0.   0.  -3. ]
 [ 0.   2.   2.  -4. ]
 [ 0.   0.   3.   4.5]
 [ 0.   0.   0.   1. ]]
[[ 1.   0.   0.   0. ]
 [ 0.   1.   0.   0. ]
 [-1.5  0.   1.   0. ]
 [ 0.   1.   0.   1. ]]


In [19]:
# Tambahkan baris indeks ke-1 yang sudah dikalikan 1/2 ke baris indeks ke-1
C3 = RowScale(C2,1,1/2)
print(C3)
I3 = RowScale(I2,1,1/2)
print(I3)

[[ 2.   0.   0.  -3. ]
 [ 0.   1.   1.  -2. ]
 [ 0.   0.   3.   4.5]
 [ 0.   0.   0.   1. ]]
[[ 1.   0.   0.   0. ]
 [ 0.   0.5  0.   0. ]
 [-1.5  0.   1.   0. ]
 [ 0.   1.   0.   1. ]]


In [24]:
# Tambahkan baris indeks ke-2 yang sudah dikalikan -1/3 ke baris indeks ke-1
C4 = RowAdd(C3,2,1,-1/3)
print(C4)
I4 = RowAdd(I3,2,1,-1/3)
print(I4)

[[ 2.   0.   0.  -3. ]
 [ 0.   1.   0.  -3.5]
 [ 0.   0.   3.   4.5]
 [ 0.   0.   0.   1. ]]
[[ 1.          0.          0.          0.        ]
 [ 0.5         0.5        -0.33333333  0.        ]
 [-1.5         0.          1.          0.        ]
 [ 0.          1.          0.          1.        ]]


In [27]:
# Tambahkan baris indeks ke-3 yang sudah dikalikan 3 ke baris indeks ke-0
C5 = RowAdd(C4,3,0,3)
print(C5)
I5 = RowAdd(I4,3,0,3)
print(I5)

[[ 2.   0.   0.   0. ]
 [ 0.   1.   0.  -3.5]
 [ 0.   0.   3.   4.5]
 [ 0.   0.   0.   1. ]]
[[ 1.          3.          0.          3.        ]
 [ 0.5         0.5        -0.33333333  0.        ]
 [-1.5         0.          1.          0.        ]
 [ 0.          1.          0.          1.        ]]


In [39]:
# Tambahkan baris indeks ke-3 yang sudah dikalikan 7/2 ke baris indeks ke-1
C6 = RowAdd(C5,3,1,7/2)
print(C6)
I6 = RowAdd(I5,3,1,7/2)
print(I6)

[[2.  0.  0.  0. ]
 [0.  1.  0.  0. ]
 [0.  0.  3.  4.5]
 [0.  0.  0.  1. ]]
[[ 1.          3.          0.          3.        ]
 [ 0.5         4.         -0.33333333  3.5       ]
 [-1.5         0.          1.          0.        ]
 [ 0.          1.          0.          1.        ]]


In [41]:
# Kalikan baris indeks-2 dengan 1/3
C7 = RowScale(C6,2,1/3)
print(C7)
I7 = RowScale(I6,2,1/3)
print(I7)

[[2.  0.  0.  0. ]
 [0.  1.  0.  0. ]
 [0.  0.  1.  1.5]
 [0.  0.  0.  1. ]]
[[ 1.          3.          0.          3.        ]
 [ 0.5         4.         -0.33333333  3.5       ]
 [-0.5         0.          0.33333333  0.        ]
 [ 0.          1.          0.          1.        ]]


In [43]:
# Tambahkan baris indeks ke-3 yang sudah dikalikan -3/2 ke baris indeks ke-2
C8 = RowAdd(C7,3,2,-3/2)
print(C8)
I8 = RowAdd(I7,3,2,-3/2)
print(I8)

[[2. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[ 1.          3.          0.          3.        ]
 [ 0.5         4.         -0.33333333  3.5       ]
 [-0.5        -1.5         0.33333333 -1.5       ]
 [ 0.          1.          0.          1.        ]]


In [45]:
# Kalikan baris indeks ke-0 dengan 1/2
C9 = RowScale(C8,0,1/2)
print(C9)
I9 = RowScale(I8,0,1/2)
print(I9)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[ 0.5         1.5         0.          1.5       ]
 [ 0.5         4.         -0.33333333  3.5       ]
 [-0.5        -1.5         0.33333333 -1.5       ]
 [ 0.          1.          0.          1.        ]]


In [52]:
# Penyelesaian = I9 x X
sol = I9 @ X
print(sol)

[[ 3.]
 [ 5.]
 [-1.]
 [ 1.]]


Jadi, $x_1 = 3$, $x_2 = 5$, $x_3 = -1$, dan $x_4 = 1$.